[settings]
npm.package_manager = "bun"

[tools]
uv = "latest"
node = "latest"
bun = "latest"
"npm:eas-cli" = "latest"
"npm:@openai/codex" = "latest"
rust = "latest"
go = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
herdr = "latest"
