[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
ruby_build_opts = "CC=gcc-14 CXX=g++-14"

[settings.npm]
bun = true

[tools]
bun = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
